{% set name = "sklearn-quantile" %}
{% set version = "0.0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dd2241b0088dbf35290b6014fb6ce2e548db8db37c6c1deb71ec04560a7297e9

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - scikit-learn >=1.0
    - packaging
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sklearn_quantile
    - sklearn_quantile.utils
    - sklearn_quantile.ensemble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/sklearn-quantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Scikit-learn compatible quantile machine learning methods
  doc_url: https://sklearn-quantile.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/sklearn-quantile

extra:
  recipe-maintainers:
    - jasperroebroek
