{% set name = "sklearn-quantile" %}
{% set py_name = "sklearn_quantile" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ py_name }}-{{ version }}.tar.gz
  sha256: 267dbba728a58f1da6b7fff7b6e8c9a87ca290b96159fa1ebddcc5f463c5361c

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools >=68
    - wheel
    - numpy >=2
    - cython >=3.0.10
    - pip
  run:
    - python
    - scikit-learn >=1.5
    - joblib
    - packaging
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sklearn_quantile
    - sklearn_quantile.utils
    - sklearn_quantile.ensemble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/sklearn-quantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Scikit-learn compatible quantile machine learning methods
  doc_url: https://sklearn-quantile.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/sklearn-quantile

extra:
  recipe-maintainers:
    - jasperroebroek
