{% set name = "sklearn-quantile" %}
{% set py_name = "sklearn_quantile" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ py_name }}-{{ version }}.tar.gz
  sha256: ff8f2e6f3008f574ed03529a1ed9721329b8492721dd742792fc975985186ae3

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<39]
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=68
    - wheel
    - numpy <2
    - cython >=0.29.21
    - pip
  run:
    - python
    - scikit-learn >=1.4
    - joblib
    - packaging
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - sklearn_quantile
    - sklearn_quantile.utils
    - sklearn_quantile.ensemble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/sklearn-quantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Scikit-learn compatible quantile machine learning methods
  doc_url: https://sklearn-quantile.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/sklearn-quantile

extra:
  recipe-maintainers:
    - jasperroebroek
