{% set name = "sklearn-quantile" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/42/3c/5150acbe7d22e91f301b7f171954eac765cd36958ade66e0f6eb39925154/sklearn-quantile-0.0.27.tar.gz
  sha256: 7d0643395c5beea2cfba8021a5f6838823eef134ce759583439868c6df1b873c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
  run:
    - python
    - scikit-learn >=1.0
    - packaging
    - {{ pin_compatible('numpy') }}
    - joblib

test:
  imports:
    - sklearn_quantile
    - sklearn_quantile.utils
    - sklearn_quantile.ensemble
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jasperroebroek/sklearn-quantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Scikit-learn compatible quantile machine learning methods
  doc_url: https://sklearn-quantile.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/jasperroebroek/sklearn-quantile

extra:
  recipe-maintainers:
    - jasperroebroek
